# Generated by Django 3.0.2 on 2020-09-04 08:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_title', models.CharField(help_text='You can enter up to 30 characters.', max_length=30)),
                ('p_name', models.CharField(help_text='You can enter up to 10 characters.', max_length=10)),
                ('p_date', models.DateField(default=datetime.date.today)),
                ('p_description', models.TextField(max_length=500)),
            ],
            options={
                'ordering': ['p_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(help_text='You can enter up to 10 characters.', max_length=10)),
                ('c_date', models.DateField(default=datetime.date.today)),
                ('c_description', models.CharField(help_text='Enter your comment. n\\You can enter up to 100 characters.', max_length=100)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dryblog.Post')),
            ],
            options={
                'ordering': ['c_date'],
            },
        ),
    ]
